# Stage 1: Build
FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod ./
COPY main.go ./
RUN go mod tidy
RUN go build -o backend main.go

# Stage 2: Run
FROM gcr.io/distroless/base-debian12
WORKDIR /root/
COPY --from=builder /app/backend .
EXPOSE 8081
CMD ["./backend"]
